### ISSUE TITLE
docker-compose: command not found

### ISSUE THREAD

**Issue by kief** [kudulab/dojo#42]
Hi folks!

```
kmorris@Kiefs-MacBook-Pro:~/src/spin/website-stack$ which docker-compose
/opt/homebrew/bin/docker-compose
kmorris@Kiefs-MacBook-Pro:~/src/spin/website-stack$ dojo
2024/06/21 15:56:41 [ 1]  INFO: (main.main) Dojo version 0.13.0
panic: Unexpected error: Command: docker-compose version --short
  Exit status: 127
  StdOut: <empty string>
  StdErr: bash: line 1: docker-compose: command not found


goroutine 1 [running]:
main.GetDockerComposeVersion({0x116a868?, 0xc0000c6080?})
	/dojo/work/src/dojo/docker_compose_driver.go:47 +0xf6
main.main()
	/dojo/work/src/dojo/main.go:92 +0x259
```

My Dojofile looks like:
```
DOJO_DOCKER_IMAGE="kiefm/spin-tools-dojo:latest"
DOJO_DRIVER="docker-compose"
DOJO_DOCKER_COMPOSE_FILE="docker-compose.yml"
```

**Comment by kief** [comment]
Poking around in the dojo code, I see where the BashShellService is created and used, but it looks to me like it sets the environment for the shell to an empty string array. I assume it would pick the environment (including PATH) from the parent shell, but I don't know enough about golang to work it out.

**Comment by xmik** [comment]
Hi there Kief!

There is a new Dojo version `0.13.3`. It would be great if you could please check if the above error still persists with that new Dojo version.

Also, I added a log message that prints the info about the environment variables (to check your theory from the above comment). To see that log output, please add the followiing at the end of your dojo command: `--log-level=debug` and look for a message that starts with: `Local enviroment variables`. Hopefully, it's not an intermitent error!

**Comment by xmik** [comment]
Closing as fixed! Feel free to reopen :)
